# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import src.adapters.data_stream_handler_pb2 as data__stream__handler__pb2


class DataStreamHandlerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.exchange_eeg_data = channel.unary_unary(
                '/Thesis.DataStreamHandler/exchange_eeg_data',
                request_serializer=data__stream__handler__pb2.Data.SerializeToString,
                response_deserializer=data__stream__handler__pb2.Param.FromString,
                )


class DataStreamHandlerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def exchange_eeg_data(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataStreamHandlerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'exchange_eeg_data': grpc.unary_unary_rpc_method_handler(
                    servicer.exchange_eeg_data,
                    request_deserializer=data__stream__handler__pb2.Data.FromString,
                    response_serializer=data__stream__handler__pb2.Param.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Thesis.DataStreamHandler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DataStreamHandler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def exchange_eeg_data(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Thesis.DataStreamHandler/exchange_eeg_data',
            data__stream__handler__pb2.Data.SerializeToString,
            data__stream__handler__pb2.Param.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
